#!/usr/bin/env python3
"""Public benchmarks as A/B experiments.

  ./agent ab import polyglot-python EXP [--repeats N] [--src CLONE]

polyglot-python: the 34 Python exercises of Aider's polyglot benchmark (Exercism problems, MIT licensed;
https://github.com/Aider-AI/polyglot-benchmark, pinned to COMMIT). Builds projects/bench-polyglot-py (stubs,
tests, instructions; the reference solutions in .meta/ are left out) and ab/EXP/spec.toml with one task per
exercise. The pristine test files are the hidden grading files, so an agent that edits the tests gains nothing.
Variants: `plain` (the harness as is) and `phase2` (fresh-checkout re-check, 2 runs, up to 2 feedback rounds).
Web search is disabled in the trials: the exercises' solutions are public.
Differences from Aider's own numbers: a Claude Code agent with tools (it can run the tests itself) instead
of Aider's edit format, so scores are comparable between variants here, not with Aider's leaderboard.
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
URL, COMMIT = "https://github.com/Aider-AI/polyglot-benchmark.git", "7e0611e77b54e2dea774cdc0aa00cf9f7ed6144f"
PROJECT = "bench-polyglot-py"
RUN_TESTS = "python3 -m unittest discover -p '*_test.py'"

PROMPT = """# {title}

{instructions}

Implement it in `exercises/{name}/{solution}` (it has the stubs). The tests are in `exercises/{name}/{test}`; run them with:

    cd exercises/{name} && {run}

Keep the existing function and class names: the tests import them. Use only the Python standard library.
Work only in `exercises/{name}/`."""


def git(*a, cwd=None):
    return subprocess.run(["git", *a], cwd=cwd, capture_output=True, text=True, check=True).stdout


def polyglot_python(exp, repeats, src):
    if not src:
        src = ROOT / "run" / "bench-src" / "polyglot-benchmark"
        if not (src / ".git").exists():
            src.parent.mkdir(parents=True, exist_ok=True)
            git("clone", "-q", URL, str(src))
    src = Path(src)
    git("fetch", "-q", "origin", COMMIT, cwd=src) if git("cat-file", "-t", COMMIT, cwd=src).strip() != "commit" else None
    git("checkout", "-q", COMMIT, cwd=src)
    practice = src / "python" / "exercises" / "practice"
    pdir = ROOT / "projects" / PROJECT
    if not (pdir / ".git").exists():
        (pdir / "exercises").mkdir(parents=True)
        for ex in sorted(practice.iterdir()):
            shutil.copytree(ex, pdir / "exercises" / ex.name, ignore=shutil.ignore_patterns(".meta"))
        (pdir / "README.md").write_text(
            f"# Benchmark: Aider polyglot, Python exercises\n\nFrom {URL} at {COMMIT} (Exercism problems, MIT licence). "
            "Reference solutions (.meta/) removed. Used by `./agent ab` experiments only; no TODO.md, so the loop "
            "and the pool never work here.\n")
        (pdir / ".gitignore").write_text("__pycache__/\n*.pyc\n")
        git("init", "-q", "-b", "main", cwd=pdir)
        git("add", "-A", cwd=pdir)
        git("-c", "user.name=kevin", "-c", "user.email=kjr64@cornell.edu", "commit", "-q", "-m",
            f"polyglot-benchmark python exercises @ {COMMIT[:9]}", cwd=pdir)
    d = ROOT / "ab" / exp
    if (d / "spec.toml").exists():
        sys.exit(f"ab/{exp}/spec.toml exists")
    tasks = []
    for ex in sorted(practice.iterdir()):
        cfg = json.loads((ex / ".meta" / "config.json").read_text())["files"]
        docs = ex / ".docs"
        instr = "\n\n".join((docs / f).read_text().strip() for f in ("instructions.md", "instructions.append.md")
                            if (docs / f).exists())
        hidden = d / "hidden" / ex.name / "exercises" / ex.name
        hidden.mkdir(parents=True)
        for f in ex.iterdir():   # everything but the solution stubs and the reference: tests and their helpers
            if f.is_file() and f.name not in cfg["solution"]:
                shutil.copy2(f, hidden / f.name)
        prompt = PROMPT.format(title=ex.name.replace("-", " ").title(), instructions=instr, name=ex.name,
                               solution=", ".join(cfg["solution"]), test=", ".join(cfg["test"]), run=RUN_TESTS)
        tasks.append(f'[[task]]\nid = "{ex.name}"\nprompt = {json.dumps(prompt)}\n'
                     f'check = {json.dumps(f"cd exercises/{ex.name} && {RUN_TESTS}")}\nhidden = "ab/{exp}/hidden/{ex.name}"\n')
    spec = f'''# Aider polyglot benchmark, Python ({len(tasks)} exercises) @ {COMMIT[:9]}: does a fresh-checkout re-check with
# feedback ("phase 2") raise the pass rate? Generated by `./agent ab import polyglot-python {exp}`.
project = "{PROJECT}"
base = "HEAD"
repeats = {repeats}
seed = 1
timeout = 900
max_turns = 80
verify_runs = 2
disallowed_tools = ["mcp__websearch__web_search", "mcp__websearch__fetch_page"]

[judge]
rubric = """Correctness first: does the code implement the instructions, including edge cases?
Then quality: clear, idiomatic Python, no needless complexity, tests left unchanged."""

[[variant]]
name = "plain"

[[variant]]
name = "phase2"
verify = {{ rounds = 2, runs = 2, feedback = "check" }}

''' + "\n".join(tasks)
    (d / "spec.toml").write_text(spec)
    print(f"projects/{PROJECT} + ab/{exp}/spec.toml: {len(tasks)} tasks x 2 variants x {repeats} repeats "
          f"= {len(tasks) * 2 * repeats} trials ({len(tasks) * repeats} pairs)")


def main(args):
    if len(args) < 2 or args[0] != "polyglot-python":
        sys.exit(__doc__)
    repeats = int(args[args.index("--repeats") + 1]) if "--repeats" in args else 3
    src = args[args.index("--src") + 1] if "--src" in args else None
    polyglot_python(args[1], repeats, src)


if __name__ == "__main__":
    main(sys.argv[1:])
